from fastapi import APIRouter, Depends, Query, HTTPException, status
from typing import Optional
from pydantic import BaseModel
from datetime import datetime
from app.db.client import get_database
from app.services.report_service import ReportService
from app.core.security import get_current_user, TokenData
from app.core.logging import logger

router = APIRouter(prefix="/reports", tags=["Reports"])


class CreateReportRequest(BaseModel):
    report_type: str  # summary, detailed, county
    title: str
    county: Optional[str] = None
    abuse_type: Optional[str] = None
    status: Optional[str] = None
    date_from: Optional[str] = None
    date_to: Optional[str] = None
    include_kenya_data: Optional[bool] = True  # Include Kenya API data in reports


@router.post("")
async def create_report(
    request: CreateReportRequest,
    current_user: TokenData = Depends(get_current_user),
    db=Depends(get_database)
):
    """
    Create a new report
    
    Now includes Kenya Child Protection API data:
    - Set include_kenya_data=true to include Kenya API statistics
    - Reports show data source breakdown (local vs Kenya API)
    - County reports include Kenya API case counts per county
    """
    try:
        report_service = ReportService(db)

        filters = {
            "county": request.county,
            "abuse_type": request.abuse_type,
            "status": request.status,
            "date_from": request.date_from,
            "date_to": request.date_to
        }

        result = await report_service.create_report(
            request.report_type,
            request.title,
            filters,
            current_user.user_id,
            include_kenya_data=request.include_kenya_data
        )

        logger.info(f"Report created by {current_user.user_id}: {result['report_id']}")
        return result

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error creating report: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Error creating report"
        )


@router.get("")
async def list_reports(
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    current_user: TokenData = Depends(get_current_user),
    db=Depends(get_database)
):
    """List reports"""
    report_service = ReportService(db)
    result = await report_service.list_reports(page, limit, current_user.user_id)

    logger.info(f"Reports listed by {current_user.user_id}")

    return {
        "total": result["total"],
        "page": result["page"],
        "limit": result["limit"],
        "reports": [
            {
                "report_id": r["report_id"],
                "title": r["title"],
                "report_type": r["report_type"],
                "status": r["status"],
                "generated_at": r["generated_at"]
            }
            for r in result["reports"]
        ]
    }


@router.get("/{report_id}")
async def get_report(
    report_id: str,
    current_user: TokenData = Depends(get_current_user),
    db=Depends(get_database)
):
    """Get report details"""
    report_service = ReportService(db)
    report = await report_service.get_report(report_id)

    # Check ownership
    if str(report["generated_by"]) != current_user.user_id and current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Cannot access report generated by another user"
        )

    logger.info(f"Report retrieved by {current_user.user_id}: {report_id}")

    return {
        "report_id": report["report_id"],
        "title": report["title"],
        "report_type": report["report_type"],
        "status": report["status"],
        "filters": report["filters"],
        "data": report["data"],
        "generated_at": report["generated_at"]
    }


@router.delete("/{report_id}")
async def delete_report(
    report_id: str,
    current_user: TokenData = Depends(get_current_user),
    db=Depends(get_database)
):
    """Delete report"""
    report_service = ReportService(db)
    report = await report_service.get_report(report_id)

    # Check ownership
    if str(report["generated_by"]) != current_user.user_id and current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Cannot delete report generated by another user"
        )

    await report_service.delete_report(report_id)
    logger.info(f"Report deleted by {current_user.user_id}: {report_id}")

    return {"message": "Report deleted successfully"}
